config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    resources :tasks
  end
  namespace :category do
    resources :tasks
  end
  devise_for :users
  root to: "categories#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.present?
      can :manage, Category, user_id: user.id
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user

  validates :title, presence: true

  def tasks_completed
    tasks.select { |task| task.completed? }.count
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :title, presence: true
  validates :status, presence: true

   STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Completed', 'completed']
  ]

  def badge_color
    case status
    when 'not-started'
        'dark'
    when 'in-progress'
        'warning text-dark'
    when 'completed'
        'success'
    end
  end

  def completed?
    status == 'completed'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories
  has_one_attached :avatar
  after_commit :avatar, on: %i[create update]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # layout :layout_by_controller

  # protected

  # def layout_by_controller
  #   devise_controller? ? 'devise' : 'application'
  # end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:avatar, :email, :password, :password_confirmation,   :current_password) } 
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    # @categories = current_user.categories
    @categories = Category.accessible_by(current_ability).all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @task = @category.tasks.build
  end

  # GET /categories/new
  def new
    @category = current_user.categories.build
    render :show_form
  end

  # GET /categories/1/edit
  def edit
    @category = current_user.categories.find(params[:id])
    render :show_form
  end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to(@category, notice: "Journal was successfully created.") and return
      render :show, status: :created, location: @category
    else
      flash.now[:messages] = @category.errors.full_messages[0]
      render :show_form
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    @category = current_user.categories.find(params[:id])
    @category.update(category_params)
    if @category.save
      redirect_to(root_path, notice: "Journal was successfully updated.") and return
      render :show, status: :created, location: @category
    else
      flash.now[:messages] = @category.errors.full_messages[0]
      render :show_form
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Journal was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET categories/1/tasks
  def index
    @tasks = @category.tasks
  end

  # GET categories/1/tasks/1
  def show
  end

  # GET categories/1/tasks/new
  def new
    @task = @category.tasks.build
  end

  # GET categories/1/tasks/1/edit
  def edit
  end

  # POST categories/1/tasks
  def create
    @task = @category.tasks.build(task_params)

    if @task.save
      redirect_to(@task.category, notice: 'Task was successfully created.')
    else
      flash.now[:messages] = @task.errors.full_messages[0]
      render action: 'new'
    end
  end

  # PUT categories/1/tasks/1
  def update
    @task.update(task_params)
    if @task.save
      redirect_to(@task.category, notice: 'Task was successfully updated.')
    else
      flash.now[:messages] = @task.errors.full_messages[0]
      render action: 'edit'
    end
  end

  # DELETE categories/1/tasks/1
  def destroy
    @task = @category.tasks.find(params[:id])
    @task.destroy

    redirect_to @category
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find(params[:category_id])
    end

    def set_task
      @task = @category.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:title, :description, :status, :category_id, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date, format = :rfc822)
    date.blank? ? '--' : date.to_s(format)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<div class="modal-header">
  <h1 class="text-dark">
    <%= @category.new_record? ? 'New Journal' : "Edit Journal" %>
  </h1>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<%= simple_form_for @category, remote: true do |f| %>
<div class="modal-body">
  <%= f.label :title, "Title", :class => "form-label text-dark" %>
  <div class="input-group mb-3">
    <%= f.input_field :title, :class => "form-control" %>
  </div>
  <%= f.label :description, "Description", :class => "form-label text-dark" %>
  <div class="input-group mb-3">
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <% if flash[:messages] %>
    <p class = "text-danger"><%= flash[:messages] %></p> <br>
  <% end %>
</div>
<div class="modal-footer">
  <%= f.submit "Add", :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/categories/index.html.erb
<h1 class="text-center mb-5">My Journal</h1>

<% if @categories.empty? %>
  <div class="card text-center w-75 mx-auto bg-dark border-dark mt-5">
    <div class="card-body text-secondary">
      <img src=<%=asset_path("empty.svg")%>/>
      <h5 class="card-title">You don't have any Journal.</h5>
      <h6 class="card-text"><%= link_to new_category_path, "data-bs-toggle" => "modal", "data-bs-target" => "#exampleModal", :remote => true do %>
        <i class="fas fa-plus text-primary"></i> Create one.
      <% end %></h6>
    </div>
  </div>
<% else %>

  <% @categories.each do |category| %>
    <div class="card w-75 bg-secondary mx-auto mb-3">
      <div class="card-body d-flex p-4">
        <div class="flex-grow-1">
          <h5 class="card-title"><%= category.title %></h5>
          <p class="card-text" style="transform: rotate(0);"><%= link_to category.description, category, :class => "text-white stretched-link" %></p>
          <div>
            <span class="text-light">
              <small>Completed <%= category.tasks_completed %> out of <%= category.tasks.count %> tasks</small>
            </span>
          </div>
        </div>
        <div class="p-2 text-center">
          <div class="dropdown text-end">
            <button class="btn btn-sm btn-outline-warning" id="dLabel" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fas fa-caret-down"></i>
            </button>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
              <li><%= link_to 'Edit', edit_category_path(category), :class => "dropdown-item", "data-bs-toggle" => "modal", "data-bs-target" => "#exampleModal", remote: true %></li>
              <li><%= link_to 'Delete', category_path(category), remote: true, method: :delete,
                :class => "dropdown-item", 
                data: {confirm: "Are you sure you want to delete this task?"} %>
              </li>
            </ul>
          </div>
        </div>
      </div> 
    </div>
  <% end %>
<% end %>

<button type="button" class="btn btn-info btn-circle btn-xl">
  <%= link_to new_category_path, :class => 'btn-create', "data-bs-toggle" => "modal", "data-bs-target" => "#exampleModal", :remote => true do %>
    <i class="fas fa-pencil-alt text-white"></i>
  <% end %>
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="w-75 mx-auto">
  <%= link_to categories_path, :class => "text-white" do %>
    <i class="fas fa-chevron-left text-secondary"><span class="back-btn"> Back</span></i>
  <% end %>
</div>

<div class="card bg-dark mx-auto mt-5 border-secondary w-75 mx-auto">
  <div class="card-body d-flex p-4">
    <div class="flex-grow-1">
      <h4 class="card-title"><%= @category.title %></h5>
      <p><%= @category.description %></p>
      <%= link_to 'Add Task', new_category_task_path(@category.id), :class => "btn btn-sm btn-secondary" %>
    </div>
    <div class="p-2 text-center">
      <div class="dropdown text-end">
        <button class="btn btn-sm btn-outline-warning" id="dLabel" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-caret-down"></i>
        </button>
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
          <li><%= link_to 'Edit', edit_category_path(@category), :class => "dropdown-item", "data-bs-toggle" => "modal", "data-bs-target" => "#exampleModal", remote: true %></li>
          <li><%= link_to 'Delete', category_path(@category), remote: true, method: :delete,
            :class => "dropdown-item", 
            data: {confirm: "Are you sure you want to delete this journal?"} %>
          </li>
        </ul>
      </div>
    </div>
  </div> 
</div>
        


<!-- Tasks -->
<div class="row w-75 mx-auto mt-4 gx-4 gy-4" data-masonry='{"percentPosition": true }'>
<% @category.tasks.each do |task| %>
  <% if @category.tasks.empty? %>
    <span class="text-warning">There are no tasks!</span>
  <% elsif task.persisted? %>
        <div class="col col-md-3">
          <div class="card bg-light text-dark">
            <div class="card-body">
              <span class="badge bg-<%= task.badge_color %> mb-3"><%= task.status %></span>
              <h5 class="card-title"> <%= task.title %></h5>
              <p class="card-text"> <%= task.description %></p>
            </div>
            <div class="card-footer">
                <small class="text-muted"><%= format_date task.deadline %></small><br>
                <%= link_to edit_category_task_path(@task.category, task) do %>
                  <i class="fas fa-edit text-success"></i>
                <% end %>
                <%= link_to [task.category, task], remote: true, method: :delete,
                  :class => "text-decoration-none", 
                  data: {confirm: "Are you sure you want to delete this task?"} do %>
                  <i class="fas fa-trash-alt text-danger"></i>
                <% end %>
            </div>
          </div>   
        </div>
        <% end %>
  <% end %>
</div>



<!-- Modals -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
    </div>
  </div>
</div>

app/views/categories/show_form.js.erb
$("#exampleModal").find(".modal-content").html("<%= j (render 'form') %>");
$("#exampleModal").modal();

app/views/layouts/_header.html.erb
<header class="pt-3 pb-2 mb-5 border-bottom border-dark w-75 mx-auto">
  <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 1fr 2fr;">
    <h2><%= link_to "Keeps", "/", class: "text-warning" %></h2>

    <div class="d-flex align-items-center">
      <div class="w-100 me-3"></div>
      <% if user_signed_in? %>
        <div class="flex-shrink-0 dropdown">
          <a href="#" class="d-block link-warning text-decoration-none dropdown-toggle" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: "rounded-circle", width: "32", height: "32" %>
            <% else %>
              <%= image_tag("default_profile.jpg", class: "rounded-circle", height: '32', width: '32') %>
            <% end %>
          </a>
          <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser">
            <li><%= link_to 'New Journal', new_category_path, :class => 'dropdown-item', "data-bs-toggle" => "modal", "data-bs-target" => "#exampleModal", :remote => true %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </div>
      <% else %>
        <div class="w-100 text-end">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-sm btn-warning' %>
        </div>
      <% end %>
      </div>
  </div>
</header>

app/views/layouts/_hero.html.erb
<div class="w-75 mx-auto">
  <div class="row p-2 p-md-5 mb-4 text-white rounded bg-dark text-center">
    <div class="col-md-6 col-sm-12 hero-text pt-4">
      <h1 class="display-4 fst-italic">
        All your tasks, <br>
        in one place.
      </h1>
      <%= link_to "Log in", "/users/sign_in", class: "btn btn-primary my-3" %><br />
    </div>
    <div class="col-md-6 col-sm-12 hero-img">
        <img src=<%=asset_path("Blogging-pana.svg")%> />
    </div>
  </div>
</div>
<footer class="mt-auto mx-auto text-white-50 w-100">
  <div class="row justify-content-center">
    <div class="col-11">
      <div class="row mb-3">
        <div class="col-xl-8 col-md-4 col-sm-4 col-auto my-md-2 mx-auto">
          <p class="social text-muted mb-0 pb-0 bold-text text-center">
            <span class="mx-2">
              <i class="fa fa-facebook" aria-hidden="true">
              </i>
            </span>
            <span class="mx-2">
              <i class="fa fa-linkedin-square" aria-hidden="true">
              </i>
            </span>
            <span class="mx-2">
              <i class="fa fa-twitter" aria-hidden="true">
              </i>
            </span>
            <span class="mx-2">
              <i class="fa fa-instagram" aria-hidden="true">
              </i>
            </span>
          </p>
        </div>
      </div>
      <div class="row">
        <small class="rights text-center"><span>&#174;</span> Keeps All Rights Reserved.</small>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Keeps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/033affd47f.js" crossorigin="anonymous"></script>   
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex h-100 text-white bg-dark">
    <% flash.each do |type, msg| %>
      <div class="alert alert-info alert-dismissible fade show mt-4 alert-fixed" role="alert">
        <%= msg %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <div class="container d-flex h-100 p-3 flex-column">
      <%= render 'layouts/header' %>
      <% if user_signed_in? %>  
        <%= yield %>
      <% else %>
        <%= render 'layouts/hero' %>
      <% end %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Keeps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/033affd47f.js" crossorigin="anonymous"></script>   
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex h-100 text-white bg-dark">
    <div class="container d-flex h-100 p-3 flex-column">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if alert%>
  <div class="alert alert-danger flash text-center w-75 mx-auto">
    <%= alert %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<div class="modal-header">
  <h1 class="text-dark">
    <%= @task.new_record? ? 'New Task' : "Edit Task" %>
  </h1>
</div>

<%= simple_form_for ([@task.category, @task]) do |f| %>
<div class="modal-body">
  <%= f.label :title, "Title", :class => "form-label text-dark" %>
  <div class="input-group mb-3">
    <%= f.input_field :title, :class => "form-control", autofocus: 'true' %>
  </div>
  <%= f.label :description, "Note", :class => "form-label text-dark" %>
  <div class="input-group mb-3">
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <%= f.label :status, "Status", :class => "form-label text-dark" %>
  <div class="mb-3">
    <%= f.select :status, Task::STATUS_OPTIONS, {}, {required: 'true', class: 'form-select'} %>
  </div>
  <%= f.label :deadline, "Deadline", :class => "form-label text-dark" %>
  <div class="input-group mb-3">
    <%= f.text_field :deadline, :class => "form-control",
      data: {
        controller: "flatpickr",
        flatpickr_alt_format: t("date.formats.long"),
        flatpickr_min_date: Time.zone.now,
        flatpickr_alt_input: true
      } %>
  </div>
  <% if flash[:messages] %>
    <p class = "text-danger"><%= flash[:messages] %></p> <br>
  <% end %>
</div>
<div class="modal-footer">
  <%= f.submit "Save", :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/tasks/edit.html.erb
<div class="w-50 mx-auto">
  <%= link_to @category, :class => "text-white" do %>
    <i class="fas fa-chevron-left text-secondary"><span class="back-btn"> Back</span></i>
  <% end %>
</div>

<div class="card border-secondary text-dark w-50 mx-auto mt-3">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.category %></td>
    <td><%= link_to 'Show', [task.category, task] %></td>
    <td><%= link_to 'Edit', edit_category_task_path(task.category, task) %></td>
    <td><%= link_to 'Destroy', [task.category, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_category_task_path(params[:category_id]) %>

app/views/tasks/new.html.erb
<div class="w-50 mx-auto">
  <%= link_to @category, :class => "text-white" do %>
    <i class="fas fa-chevron-left text-secondary"><span class="back-btn"> Back</span></i>
  <% end %>
</div>

<div class="card border-secondary text-dark w-50 mx-auto mt-3">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Category:</b>
  <%= @task.category %>
</p>


<%= link_to 'Edit', edit_category_task_path(@task.category, @task) %> |
<%= link_to 'Back', category_tasks_path(@task.category) %>